apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.OCIR_TENANCY}}/bradegler/emblem-sample:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.OCIR_TENANCY}}/bradegler/emblem-sample:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: emblem-sample
        chartPath: charts/emblem-sample
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.OCIR_TENANCY}}/bradegler/emblem-sample'
          image.tag: '{{.DIGEST_HEX}}'
